# Generated by Django 4.0.3 on 2022-04-26 09:47

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sisis_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sisisnailsuser',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
